#spring.application.name=myevent-be


server:
  port: 8080
  servlet:
    context-path: /event-management

spring:
  datasource:
    url: jdbc:sqlserver://localhost:31622;databaseName=event-management8;encrypt=false;trustServerCertificate=true
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ngohuyen.280703@gmail.com
    password: auif imfh peqb oabd
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
    default-encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
      lo  cation: ${java.io.tmpdir}
   # Thêm dòng này
  file:
    upload-dir: /uploads
jwt:
  signerKey: "qqziwod2yMQH8iDEZ/893gnzz4KtX4YDKnJz7OuQ/rSjdRssiWWtynVHhmERdhs7"
  valid-duration: 20 #in second
  refreshable-duration: 600 # in seconds

